name: Registre diari de temperatures

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  temperatura:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositori
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Llista fitxers i carpetes del repositori
        run: ls -R
        
      - name: Instal·la llibreries
        run: |
          pip install openmeteo-requests pandas requests-cache retry-requests

      - name: Executa el script
        run: python "ProjecteGitHub-Actions(part2)/GitHub_Actions.py"

      - name: Mou el fitxer JSON a la carpeta del projecte
        run: |
          mkdir -p "ProjecteGitHub-Actions(part2)/Registre-Temps-Diari"
          mv temperatures_*.json "ProjecteGitHub-Actions(part2)/Registre-Temps-Diari/"

      - name: Configura Git per push
        run: |
          git config user.name "MarcGomezRufas"
          git config user.email "marc.gomez22@lacetania.cat"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/MarcGomezRufas/Registre-Temps-Diari.git

      - name: Fes commit i push
        run: |
          git add "ProjecteGitHub-Actions(part2)/Registre-Temps-Diari/temperatures_*.json"
          git commit -m "Afegit fitxer json diari dins la subcarpeta Registre-Temps-Diari"
          git push origin main
